import { useMemo, useState } from "react";
import "@/progress-report.css";
import { ArrowLeft, Printer } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useAppStore } from "@/lib/AppStore";
import { finalGradeRounded, getAssessments } from "@/lib/calculations";
import { getStoredSession, type CloudConfig } from "@/lib/cloudSync";
import { getCourseArea, getPlanCoursesForDegree } from "@/lib/uabPlan";
import { formatPtNumber } from "@/lib/utils";
import type { Assessment, Course } from "@/lib/types";

const LOGO="/academic-hub-icon-v10-192.png";
type PrintOrientation="portrait"|"landscape";
function score(a?:Assessment|null){return !a||a.grade===null?"—":`${formatPtNumber(a.grade)}/${formatPtNumber(a.maxPoints)}`}
function sortCourses(a:Course,b:Course){return a.year-b.year||a.semester-b.semester||a.code.localeCompare(b.code,"pt-PT")}
function Student({name,id,avatar}:{name:string;id:string;avatar?:string}){const ini=name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();return <div className="pr-student">{avatar?<img src={avatar} alt="Fotografia do aluno"/>:<div className="pr-avatar">{ini}</div>}<div><strong>{name}</strong><span>N.º estudante: {id||"—"}</span></div></div>}
function Brand(){return <div className="pr-brand"><img src={LOGO} alt="Academic Hub"/><div><strong>Academic Hub</strong><span>Gestão académica pessoal</span></div></div>}
function Disclaimer(){return <div className="pr-disclaimer"><b>i</b><span><strong>Documento pessoal de acompanhamento académico.</strong> Não substitui qualquer declaração, certidão, diploma ou Carta de Curso emitidos oficialmente pela Universidade Aberta.</span></div>}
export default function AcademicProgressReport(){const nav=useNavigate();const{state}=useAppStore();const[stamp,setStamp]=useState(new Date());const[orientation,setOrientation]=useState<PrintOrientation>("landscape");const plan=useMemo(()=>getPlanCoursesForDegree(state.degree),[state.degree]);const completed=useMemo(()=>state.courses.filter(c=>c.isCompleted).sort(sortCourses),[state.courses]);const session=useMemo(()=>{const u=(import.meta.env.VITE_SUPABASE_URL||"").trim(),k=(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY||"").trim();return u&&k?getStoredSession({supabaseUrl:u,supabaseAnonKey:k} as CloudConfig):null},[]);const name=state.profile?.displayName?.trim()||"Aluno",id=session?.user.email?.split("@")[0]||"",avatar=state.profile?.avatarUrl?.trim()||undefined;const rows=useMemo(()=>completed.map(course=>{const p=plan.find(x=>x.code===course.code),ass=getAssessments(state,course.id),ef=ass.filter(a=>a.type==="efolio").sort((a,b)=>(a.order??999)-(b.order??999)),exam=ass.find(a=>a.type==="exam")??null,resit=ass.find(a=>a.type==="resit")??null;return{course,area:getCourseArea(plan,course.code)||"Outras",ects:p?.ects??0,ef,exam,resit,final:finalGradeRounded(state,course.id)}}),[completed,plan,state]);const totalEcts=plan.reduce((s,c)=>s+(c.ects||0),0)||180,doneEcts=rows.reduce((s,r)=>s+r.ects,0),pct=Math.min(100,Math.round(doneEcts/totalEcts*100)),grades=rows.map(r=>r.final).filter((v):v is number=>v!==null),avg=grades.length?grades.reduce((a,b)=>a+b,0)/grades.length:null;const groups=useMemo(()=>{const m=new Map<string,typeof rows>();for(const r of rows){const a=m.get(r.area)||[];a.push(r);m.set(r.area,a)}return [...m.entries()].sort(([a],[b])=>a.localeCompare(b,"pt-PT"))},[rows]);const date=stamp.toLocaleDateString("pt-PT",{day:"2-digit",month:"long",year:"numeric"});const chooseOrientation=(value:PrintOrientation)=>{setOrientation(value);document.documentElement.dataset.progressReportOrientation=value};const print=()=>{document.documentElement.dataset.progressReportOrientation=orientation;setStamp(new Date());setTimeout(()=>window.print(),60)};return <div className={`pr-view pr-${orientation}`}><div className="pr-actions print:hidden"><Button variant="outline" className="pr-back-button" onClick={()=>nav(-1)}><ArrowLeft className="mr-2 h-4 w-4"/>Cancelar e voltar</Button><div className="pr-action-right"><span className="pr-orientation-label">Orientação:</span><Button type="button" variant={orientation==="portrait"?"default":"outline"} onClick={()=>chooseOrientation("portrait")}>A4 vertical</Button><Button type="button" variant={orientation==="landscape"?"default":"outline"} onClick={()=>chooseOrientation("landscape")}>A4 horizontal</Button><Button onClick={print}><Printer className="mr-2 h-4 w-4"/>Imprimir ou guardar em PDF</Button></div></div>
<section className="pr-page"><header><Brand/><Student name={name} id={id} avatar={avatar}/><div className="pr-date"><span>Data de emissão</span><strong>{date}</strong></div></header><div className="pr-title"><span>▣</span><div><h1>RELATÓRIO ACADÉMICO</h1><p>Acompanhamento do percurso académico</p></div></div><div className="pr-info-grid"><div><span>Curso</span><strong>{state.degree?.name||"Curso não definido"}</strong></div><div><span>ECTS concluídos</span><strong>{doneEcts} <small>de {totalEcts}</small></strong></div><div><span>Progresso do curso</span><strong>{pct}%</strong><i><em style={{width:`${pct}%`}}/></i></div><div><span>Instituição</span><strong>Universidade Aberta</strong></div><div><span>Média atual</span><strong>{avg===null?"—":`${formatPtNumber(avg,1)} valores`}</strong></div><div><span>Cadeiras concluídas</span><strong>{completed.length} <small>de {plan.length||state.courses.length}</small></strong></div></div><div className="pr-summary"><div><span>▣</span><small>Cadeiras concluídas</small><strong>{completed.length}</strong></div><div><span>▤</span><small>ECTS concluídos</small><strong>{doneEcts} <small>de {totalEcts}</small></strong></div><div><span>↗</span><small>Média atual</small><strong>{avg===null?"—":formatPtNumber(avg,1)}</strong></div><div><span>◷</span><small>Estado</small><strong>{pct===100?"Concluído":"Em curso"}</strong></div></div><div className="pr-lower"><div><h3>DISTRIBUIÇÃO DE ECTS</h3><div className="pr-progress"><strong>{pct}%</strong><div><span>ECTS concluídos: <b>{doneEcts}</b></span><i><em style={{width:`${pct}%`}}/></i><span>ECTS em falta: <b>{Math.max(0,totalEcts-doneEcts)}</b></span></div></div></div><div className="pr-message"><b>★</b><div><strong>{pct===100?"PERCURSO CONCLUÍDO":"CONTINUE A AVANÇAR!"}</strong><p>{pct===100?"Parabéns pela conclusão do percurso académico.":"O progresso é construído cadeira a cadeira. Continue a registar o seu percurso."}</p></div></div></div><Disclaimer/><footer><Brand/><span>Página 1 de 2</span></footer></section>
<section className="pr-page pr-detail"><header><Brand/><Student name={name} id={id} avatar={avatar}/></header><div className="pr-title"><span>▣</span><div><h1>DETALHE DO PERCURSO ACADÉMICO</h1><p>Cadeiras concluídas e avaliações, agrupadas por categoria</p></div></div>{groups.length===0?<div className="pr-empty">Ainda não existem cadeiras concluídas.</div>:groups.map(([area,items])=><div className="pr-category" key={area}><div className="pr-category-head"><strong>{area}</strong><span>{items.length} {items.length===1?"cadeira":"cadeiras"} · {items.reduce((s,r)=>s+r.ects,0)} ECTS</span></div><table><thead><tr><th>Código</th><th>Unidade Curricular</th><th>Ano/Sem.</th><th>ECTS</th><th>E-fólios</th><th>Avaliação final</th><th>Nota</th><th>Conclusão</th></tr></thead><tbody>{items.map(r=><tr key={r.course.id}><td>{r.course.code}</td><td>{r.course.name}</td><td>{r.course.year}º/{r.course.semester}º</td><td>{r.ects||"—"}</td><td>{r.ef.length?r.ef.map(score).join(" · "):"—"}</td><td>{r.resit?.grade!==null&&r.resit?`R ${score(r.resit)}`:score(r.exam)}</td><td><strong>{r.final===null?"—":formatPtNumber(r.final)}</strong></td><td>{r.course.completedAt?new Date(r.course.completedAt).toLocaleDateString("pt-PT"):"—"}</td></tr>)}</tbody></table></div>)}<Disclaimer/><footer><Brand/><span>Página 2 de 2</span></footer></section></div>}
