import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowRight, BookOpen, CalendarDays, CheckCircle2, Cloud, ExternalLink, FileText, GraduationCap, HelpCircle, LayoutDashboard, LifeBuoy, LockKeyhole, Printer, Scale, Settings, Sparkles, UserPlus, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
const REGULATION_URL="https://portal.uab.pt/avaliacao/";
const guides=[{title:"Primeiros passos",description:"Escolher a licenciatura, carregar o plano e ativar as cadeiras do semestre.",icon:GraduationCap},{title:"Como usar o Academic Hub",description:"Visão geral do painel, calendário, plano de estudos, histórico e alertas.",icon:LayoutDashboard},{title:"Como funciona a avaliação",description:"Regime oficial em vigor, configuração por cadeira, mínimos, exame e recurso.",icon:BookOpen},{title:"Backup e sincronização",description:"Guardar, recuperar e sincronizar os dados com segurança entre dispositivos.",icon:Cloud},{title:"Personalização",description:"Fotografia, licenciatura, modo claro, escuro ou automático e notificações.",icon:Settings},{title:"Perguntas frequentes",description:"Respostas rápidas sobre notas, cadeiras, dados, instalação e atualizações.",icon:HelpCircle}];
const steps=[
{title:"1. Explora antes de criares conta",icon:LayoutDashboard,text:"Podes conhecer a estrutura do Academic Hub, consultar cursos, plano, cadeiras e ligações públicas sem criar conta. As ações pessoais ficam protegidas até aderires.",action:"Explorar o início",to:"/"},
{title:"2. Escolhe a tua licenciatura",icon:GraduationCap,text:"Em Definições escolhe o curso. O Academic Hub passa a apresentar o plano, anos, semestres, áreas e ECTS correspondentes.",action:"Ver cursos e definições",to:"/definicoes"},
{title:"3. Consulta as cadeiras",icon:BookOpen,text:"Abre Cadeiras para conheceres as unidades curriculares. Depois de criares conta, podes ativar apenas as que estás realmente a frequentar.",action:"Ver cadeiras",to:"/cadeiras"},
{title:"4. Ativa e acompanha",icon:CheckCircle2,text:"Com conta criada, ativa uma cadeira e regista e-fólios, exame, recurso e datas. O painel calcula o progresso e ajuda a perceber o estado da avaliação.",locked:true,action:"Criar conta / entrar",to:"/conta"},
{title:"5. Organiza prazos",icon:CalendarDays,text:"O Calendário reúne datas académicas e acontecimentos das cadeiras para que tenhas uma visão temporal do semestre.",action:"Abrir calendário",to:"/calendario"},
{title:"6. Consulta o teu percurso",icon:Printer,text:"À medida que concluis cadeiras, o Histórico e os relatórios pessoais mostram ECTS, média, progresso e detalhe das avaliações. Estes documentos não substituem documentos oficiais da UAb.",locked:true,action:"Ver histórico",to:"/historico"},
{title:"7. Protege os teus dados",icon:Cloud,text:"Na área Conta e Perfil podes usar sincronização cloud, gerir a tua conta e fotografia e manter o percurso disponível nos teus dispositivos.",locked:true,action:"Conta e Perfil",to:"/conta"}
];
export default function HelpPage(){const[open,setOpen]=useState(false);const[step,setStep]=useState(0);const current=steps[step];const Icon=current.icon;return <div className="space-y-5">
<div><Button asChild variant="ghost" size="sm"><Link to="/"><ArrowLeft className="mr-2 h-4 w-4"/>Voltar ao início</Link></Button></div>
<section className="premium-surface overflow-hidden p-5 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="max-w-2xl"><div className="mb-2 inline-flex items-center gap-2 rounded-full border bg-card px-3 py-1 text-xs text-muted-foreground"><LifeBuoy className="h-3.5 w-3.5 text-primary"/>Centro de apoio</div><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Ajuda & Guia</h1><p className="mt-2 text-sm text-muted-foreground">Aprende a explorar, configurar e utilizar o Academic Hub ao teu ritmo.</p></div><Button asChild variant="outline"><Link to="/definicoes">Abrir Definições</Link></Button></div></section>
<Card className="premium-card overflow-hidden border-[hsl(var(--gold)/0.45)]"><CardContent className="grid gap-0 p-0 md:grid-cols-[1fr_auto]"><div className="p-5 sm:p-6"><div className="flex items-start gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[hsl(var(--gold-soft))] text-[hsl(var(--gold))]"><Sparkles className="h-6 w-6"/></div><div><div className="text-xs font-semibold uppercase tracking-wide text-[hsl(var(--gold))]">Novo no Academic Hub?</div><h2 className="mt-1 text-lg font-semibold">Como começar — guia passo a passo</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Vê um exemplo simples desde a escolha do curso até à ativação das cadeiras, avaliações, calendário, histórico e sincronização. Ideal também para quem está apenas a explorar.</p></div></div></div><div className="flex items-center border-t bg-[hsl(var(--gold-soft)/0.45)] p-4 md:border-l md:border-t-0"><Button className="w-full md:w-auto" onClick={()=>{setStep(0);setOpen(true)}}>Começar guia <ArrowRight className="ml-2 h-4 w-4"/></Button></div></CardContent></Card>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{guides.map(({title,description,icon:GuideIcon})=><Card key={title} className="premium-card h-full"><CardHeader className="pb-2"><div className="mb-2 flex h-10 w-10 items-center justify-center rounded-xl border bg-primary/5 text-primary dark:bg-primary/10"><GuideIcon className="h-5 w-5"/></div><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">{description}</CardContent></Card>)}</div>
<Card className="premium-card border-[hsl(var(--gold)/0.35)]"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UserRound className="h-5 w-5 text-[hsl(var(--gold))]"/>Sobre o projeto</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-muted-foreground"><p className="font-medium text-foreground">Criado e desenvolvido por Sérgio Neto, aluno da Licenciatura em Engenharia Informática da Universidade Aberta.</p><p>O Academic Hub nasceu como uma ferramenta pessoal para organizar cadeiras, avaliações, calendário e progresso académico.</p></CardContent></Card>
<div className="grid gap-4 lg:grid-cols-2"><Card className="premium-card border-primary/25"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Scale className="h-5 w-5 text-primary"/>Legal, privacidade e utilização</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground"><p>Consulta os compromissos do criador, responsabilidades do utilizador, privacidade, fotografias e limites dos relatórios.</p><Button asChild variant="outline"><Link to="/legal">Consultar informação legal</Link></Button></CardContent></Card><Card className="premium-card border-primary/25"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Printer className="h-5 w-5 text-primary"/>Relatório académico pessoal</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground"><p>Imprime ou guarda em PDF o percurso registado, incluindo avaliações, nota final e ECTS.</p><Button asChild variant="outline"><Link to="/historico/relatorio">Abrir relatório</Link></Button></CardContent></Card></div>
<Card className="premium-card overflow-hidden border-[hsl(var(--gold)/0.45)]"><CardContent className="p-0"><div className="grid md:grid-cols-[1fr_auto]"><div className="p-5 sm:p-6"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[hsl(var(--gold-soft))] text-[hsl(var(--gold))]"><FileText className="h-5 w-5"/></div><div><h2 className="font-semibold">Regulamento de avaliação atualmente publicado</h2><p className="mt-1 text-sm text-muted-foreground">Confirma sempre as regras aplicáveis no PUC e na informação oficial da Universidade Aberta.</p></div></div></div><div className="flex items-center border-t bg-[hsl(var(--gold-soft)/0.55)] p-4 md:border-l md:border-t-0"><Button asChild className="w-full md:w-auto"><a href={REGULATION_URL} target="_blank" rel="noopener noreferrer">Consultar na UAb <ExternalLink className="ml-2 h-4 w-4"/></a></Button></div></div></CardContent></Card>
<Card className="premium-card"><CardHeader><CardTitle className="text-base">Ligações úteis</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4"><a className="rounded-lg border p-3 hover:bg-accent" href="https://portal.uab.pt/" target="_blank" rel="noopener noreferrer">Portal UAb</a><a className="rounded-lg border p-3 hover:bg-accent" href="https://guiadoscursos.uab.pt/" target="_blank" rel="noopener noreferrer">Guia dos Cursos</a><a className="rounded-lg border p-3 hover:bg-accent" href="https://portal.uab.pt/calendario-letivo/" target="_blank" rel="noopener noreferrer">Calendário letivo</a><a className="rounded-lg border p-3 hover:bg-accent" href="https://www.dges.gov.pt/" target="_blank" rel="noopener noreferrer">DGES</a></CardContent></Card>
<Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-xl"><DialogHeader><div className="mb-2 flex items-center justify-between gap-3"><span className="text-xs font-semibold text-[hsl(var(--gold))]">Passo {step+1} de {steps.length}</span>{current.locked&&<span className="inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[10px] text-muted-foreground"><LockKeyhole className="h-3 w-3"/>Requer conta para alterar dados</span>}</div><DialogTitle className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5"/></span>{current.title}</DialogTitle><DialogDescription className="pt-3 text-sm leading-6">{current.text}</DialogDescription></DialogHeader><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-[hsl(var(--gold))] transition-all" style={{width:`${((step+1)/steps.length)*100}%`}}/></div><div><Button asChild variant="outline" size="sm" onClick={()=>setOpen(false)}>{current.to==="/conta"?<Link to="/definicoes?conta=criar"><UserPlus className="mr-2 h-4 w-4"/>{current.action}</Link>:<Link to={current.to}>{current.action}<ExternalLink className="ml-2 h-3.5 w-3.5"/></Link>}</Button></div><DialogFooter className="flex-row justify-between sm:justify-between"><Button variant="ghost" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))}><ArrowLeft className="mr-2 h-4 w-4"/>Anterior</Button>{step<steps.length-1?<Button onClick={()=>setStep(s=>Math.min(steps.length-1,s+1))}>Seguinte<ArrowRight className="ml-2 h-4 w-4"/></Button>:<Button onClick={()=>setOpen(false)}>Concluir guia</Button>}</DialogFooter></DialogContent></Dialog>
</div>}
