import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Cloud, Download, LogIn, MailCheck, RefreshCw, ShieldCheck, Upload, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import { toast } from "@/components/ui/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { useAppStore } from "@/lib/AppStore";
import type { AppState } from "@/lib/types";
import { type AccountMigrationStatus, type AuthSession, type CloudConfig, UAB_STUDENT_EMAIL_DOMAIN, deleteUserAccount, fetchRemoteState, getOrCreateAccountMigrationStatus, getStoredSession, isUabStudentEmail, refreshSession, requestAccountEmailChange, signIn, signUp, storeSession, upsertRemoteState } from "@/lib/cloudSync";
import { clearCloudConflict, getDeviceId, getDeviceLabel, normalizeCloudState, setSyncBaseline } from "@/lib/cloudSyncState";
import { APP_VERSION } from "@/lib/version";

type AuthMode = "overview" | "signup" | "signin" | "confirmation";
type PendingCloudAction = "upload" | "download" | "enable" | null;
function formatDate(value?: string | null) { if (!value) return ""; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("pt-PT", { day: "2-digit", month: "long", year: "numeric" }); }
function downloadBackup(filename: string, text: string) { const blob = new Blob([text], { type: "application/json;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href=url; anchor.download=filename; document.body.appendChild(anchor); anchor.click(); anchor.remove(); setTimeout(()=>URL.revokeObjectURL(url),3000); }

export default function CloudAccountPanel() {
 const { state,setSync,exportData,replaceState,resetData }=useAppStore();
 const cloudConfig:CloudConfig|null=useMemo(()=>{const u=(import.meta.env.VITE_SUPABASE_URL||"").trim();const k=(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY||"").trim();return u&&k?{supabaseUrl:u,supabaseAnonKey:k}:null;},[]);
 const [session,setSession]=useState<AuthSession|null>(null),[authMode,setAuthMode]=useState<AuthMode>("overview"),[signupEmail,setSignupEmail]=useState(""),[signupPassword,setSignupPassword]=useState(""),[signinEmail,setSigninEmail]=useState(""),[signinPassword,setSigninPassword]=useState(""),[confirmationEmail,setConfirmationEmail]=useState(""),[authBusy,setAuthBusy]=useState(false),[resetBusy,setResetBusy]=useState(false);
 const [migrationStatus,setMigrationStatus]=useState<AccountMigrationStatus|null>(null),[migrationBusy,setMigrationBusy]=useState(false),[migrationEmail,setMigrationEmail]=useState(""),[migrationRequestedEmail,setMigrationRequestedEmail]=useState(""),[pendingCloudAction,setPendingCloudAction]=useState<PendingCloudAction>(null);
 const [cloudBusy,setCloudBusy]=useState<"upload"|"download"|null>(null),[deleteMode,setDeleteMode]=useState(false),[deleteConfirmation,setDeleteConfirmation]=useState(""),[deleting,setDeleting]=useState(false);
 const isLegacyAccount=Boolean(session&&!isUabStudentEmail(session.user.email)); const deadlineExpired=Boolean(migrationStatus?.deadline&&new Date(migrationStatus.deadline).getTime()<=Date.now());
 const loadMigrationStatus=async(current:AuthSession)=>{if(!cloudConfig||isUabStudentEmail(current.user.email)){setMigrationStatus(null);return null;}try{const status=await getOrCreateAccountMigrationStatus(cloudConfig,current);setMigrationStatus(status);return status;}catch(error){console.warn("[CloudAccount]",error);return null;}};
 useEffect(()=>{if(!cloudConfig){setSession(null);return;}const stored=getStoredSession(cloudConfig);setSession(stored);if(stored){setSigninEmail(stored.user.email??"");void loadMigrationStatus(stored);}},[cloudConfig]);
 const ensureFreshSession=async()=>{if(!cloudConfig||!session)throw new Error("Sem sessão.");try{const fresh=await refreshSession(cloudConfig,session);storeSession(cloudConfig,fresh);setSession(fresh);await loadMigrationStatus(fresh);return fresh;}catch{return session;}};
 const saveLocalBackup=()=>{const stamp=new Date().toISOString().slice(0,19).replace(/[:T]/g,"-");downloadBackup(`academic-hub-backup-${stamp}.json`,exportData());toast({title:"Backup criado",description:"Os dados locais foram exportados em formato JSON."});};
 const handleSignUp=async()=>{if(!cloudConfig)return;try{setAuthBusy(true);const result=await signUp(cloudConfig,signupEmail,signupPassword);const email=signupEmail.trim().toLowerCase();if(result.confirmationRequired){setConfirmationEmail(email);setAuthMode("confirmation");setSignupPassword("");return;}if(result.session){storeSession(cloudConfig,result.session);setSession(result.session);setAuthMode("overview");setSignupPassword("");toast({title:"Conta criada",description:"A conta UAb foi criada e a sessão está ativa."});}}catch(error){toast({title:"Não foi possível criar a conta",description:error instanceof Error?error.message:"Erro inesperado.",variant:"destructive"});}finally{setAuthBusy(false);}};
 const handleSignIn=async()=>{if(!cloudConfig)return;try{setAuthBusy(true);const next=await signIn(cloudConfig,signinEmail,signinPassword);storeSession(cloudConfig,next);setSession(next);setSigninPassword("");setAuthMode("overview");const status=await loadMigrationStatus(next);toast(!isUabStudentEmail(next.user.email)?{title:"Conta em regularização",description:status?.deadline?`Atualiza o email para @${UAB_STUDENT_EMAIL_DOMAIN} até ${formatDate(status.deadline)}.`:`Atualiza o email para @${UAB_STUDENT_EMAIL_DOMAIN}.`}:{title:"Sessão iniciada",description:"Conta institucional UAb verificada."});}catch(error){toast({title:"Falha ao entrar",description:error instanceof Error?error.message:"Erro inesperado.",variant:"destructive"});}finally{setAuthBusy(false);}};
 const handleSignOut=()=>{if(!cloudConfig)return;storeSession(cloudConfig,null);setSession(null);setMigrationStatus(null);setPendingCloudAction(null);setSync({enabled:false});setAuthMode("overview");};
 const resendConfirmation=async()=>{if(!confirmationEmail)return;try{setAuthBusy(true);const{error}=await supabase.auth.resend({type:"signup",email:confirmationEmail,options:{emailRedirectTo:window.location.origin}});if(error)throw error;toast({title:"Email reenviado"});}finally{setAuthBusy(false);}};
 const handleForgotPassword=async()=>{const email=signinEmail.trim();if(!email)return;try{setResetBusy(true);await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});toast({title:"Pedido enviado",description:"Se existir uma conta com este email, receberás uma mensagem."});}finally{setResetBusy(false);}};
 const requestMigration=async()=>{if(!cloudConfig||!session)return;try{setMigrationBusy(true);const fresh=await ensureFreshSession();await requestAccountEmailChange(cloudConfig,fresh,migrationEmail);setMigrationRequestedEmail(migrationEmail.trim().toLowerCase());setMigrationEmail("");toast({title:"Alteração de email iniciada"});}finally{setMigrationBusy(false);}};
 const verifyMigration=async()=>{if(!cloudConfig||!session)return;try{setMigrationBusy(true);const fresh=await refreshSession(cloudConfig,session);storeSession(cloudConfig,fresh);setSession(fresh);if(isUabStudentEmail(fresh.user.email)){setMigrationStatus(null);setMigrationRequestedEmail("");toast({title:"Conta regularizada"});}else await loadMigrationStatus(fresh);}finally{setMigrationBusy(false);}};
 const executeCloudAction=async(action:Exclude<PendingCloudAction,null>)=>{if(!cloudConfig||!session)return;if(action==="enable"){setSync({enabled:true});return;}try{setCloudBusy(action);const fresh=await ensureFreshSession();if(action==="upload"){const raw=normalizeCloudState(JSON.parse(exportData()));const prepared={...raw,meta:{...(raw.meta??{}),appVersion:APP_VERSION},sync:{...(raw.sync??{enabled:true}),enabled:true},syncMeta:{deviceId:getDeviceId(),deviceLabel:getDeviceLabel()}} as AppState;const saved=await upsertRemoteState(cloudConfig,fresh,prepared);const finalState={...prepared,sync:{...(prepared.sync??{enabled:true}),enabled:true,lastSyncAt:saved.updated_at||new Date().toISOString()}} as AppState;setSyncBaseline(finalState);clearCloudConflict();replaceState(finalState);toast({title:"Upload concluído",description:"Esta versão é agora a referência da cloud."});}else{const remote=await fetchRemoteState(cloudConfig,fresh);if(!remote?.state){toast({title:"Sem dados na cloud"});return;}const normalized=normalizeCloudState(remote.state);const finalState={...normalized,meta:{...(normalized.meta??{}),appVersion:APP_VERSION},sync:{...(normalized.sync??{enabled:true}),enabled:true,lastSyncAt:remote.updated_at}} as AppState;setSyncBaseline(finalState);clearCloudConflict();replaceState(finalState);toast({title:"Download concluído",description:"Os dados atuais da cloud foram aplicados neste dispositivo."});}}catch(error){toast({title:action==="upload"?"Falha no upload":"Falha no download",description:error instanceof Error?error.message:"Erro inesperado.",variant:"destructive"});}finally{setCloudBusy(null);}};
 const requestCloudAction=async(action:Exclude<PendingCloudAction,null>)=>{if(!session){setAuthMode("signin");return;}if(!isUabStudentEmail(session.user.email)){await loadMigrationStatus(session);setPendingCloudAction(action);return;}await executeCloudAction(action);};
 const continueLegacyAction=async()=>{if(!pendingCloudAction||deadlineExpired)return;const action=pendingCloudAction;setPendingCloudAction(null);await executeCloudAction(action);};
 const handleSyncToggle=async(checked:boolean)=>{if(!checked){setSync({enabled:false});return;}await requestCloudAction("enable");};
 const handleDeleteAccount=async()=>{if(!cloudConfig||!session||deleteConfirmation!=="apagar")return;try{setDeleting(true);const fresh=await ensureFreshSession();await deleteUserAccount(cloudConfig,fresh);storeSession(cloudConfig,null);setSession(null);resetData();setDeleteMode(false);setDeleteConfirmation("");toast({title:"Conta eliminada"});}finally{setDeleting(false);}};
 if(!cloudConfig)return <Card className="premium-card border-destructive/35"><CardHeader><CardTitle className="text-base">Conta e sincronização</CardTitle></CardHeader><CardContent>Sincronização indisponível.</CardContent></Card>;
 return <Card className="premium-card overflow-hidden"><CardHeader className="border-b bg-muted/20"><CardTitle className="flex items-center gap-2 text-base"><Cloud className="h-4 w-4 text-primary"/>Conta e sincronização</CardTitle></CardHeader><CardContent className="space-y-5 p-4 sm:p-5">
 {!session&&authMode==="overview"&&<div className="space-y-4"><p className="text-sm text-muted-foreground">A conta permite guardar os dados na cloud e utilizá-los em vários dispositivos.</p><div className="flex gap-2"><Button onClick={()=>setAuthMode("signup")}><UserPlus className="mr-2 h-4 w-4"/>Criar conta</Button><Button variant="outline" onClick={()=>setAuthMode("signin")}><LogIn className="mr-2 h-4 w-4"/>Entrar</Button></div></div>}
 {!session&&authMode==="signup"&&<div className="space-y-3"><Label>Email institucional</Label><Input type="email" value={signupEmail} onChange={e=>setSignupEmail(e.target.value)}/><Label>Password</Label><Input type="password" value={signupPassword} onChange={e=>setSignupPassword(e.target.value)}/><Button onClick={handleSignUp} disabled={authBusy}>Criar conta</Button><Button variant="outline" onClick={()=>setAuthMode("overview")}>Cancelar</Button></div>}
 {!session&&authMode==="confirmation"&&<div className="space-y-3"><MailCheck/><p>Confirma o email enviado para {confirmationEmail}.</p><Button onClick={resendConfirmation}>Reenviar email</Button><Button variant="outline" onClick={()=>setAuthMode("signin")}>Já confirmei / Entrar</Button></div>}
 {!session&&authMode==="signin"&&<div className="space-y-3"><Label>Email</Label><Input type="email" value={signinEmail} onChange={e=>setSigninEmail(e.target.value)}/><Label>Password</Label><Input type="password" value={signinPassword} onChange={e=>setSigninPassword(e.target.value)}/><Button onClick={handleSignIn} disabled={authBusy}>Entrar</Button><Button variant="link" onClick={handleForgotPassword} disabled={resetBusy}>Esqueci-me da password</Button></div>}
 {session&&<><div className="flex items-center justify-between rounded-xl border p-4"><div><div className="text-xs text-muted-foreground">Conta ligada</div><div className="font-semibold">{session.user.email}</div><div className="mt-1 text-xs">{isLegacyAccount?<span className="text-amber-600">Regularização necessária</span>:<span className="text-emerald-600"><CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>Email UAb verificado</span>}</div></div><Button variant="outline" size="sm" onClick={handleSignOut}>Sair</Button></div>
 {isLegacyAccount&&<div className="rounded-xl border border-amber-500/40 p-4"><AlertTriangle className="mb-2"/><p className="text-sm">Atualiza para o email @{UAB_STUDENT_EMAIL_DOMAIN}.</p><Input className="mt-3" value={migrationEmail} onChange={e=>setMigrationEmail(e.target.value)}/><Button className="mt-2" onClick={requestMigration} disabled={migrationBusy}>Atualizar email</Button>{migrationRequestedEmail&&<Button variant="secondary" className="ml-2 mt-2" onClick={verifyMigration}><RefreshCw className="mr-2 h-4 w-4"/>Verificar</Button>}{pendingCloudAction&&!deadlineExpired&&<Button variant="outline" className="ml-2 mt-2" onClick={continueLegacyAction}>Continuar desta vez</Button>}</div>}
 <Separator/><div className="space-y-3"><div className="flex items-center justify-between"><div><div className="text-sm font-medium">Sincronização automática</div><div className="text-xs text-muted-foreground">Mantém os dados iguais nos teus dispositivos.</div></div><Switch checked={Boolean(state.sync?.enabled)} onCheckedChange={handleSyncToggle}/></div>{state.sync?.lastSyncAt&&<div className="text-xs text-muted-foreground">Última sincronização: {new Date(state.sync.lastSyncAt).toLocaleString("pt-PT")}</div>}<div className="flex flex-wrap gap-2"><Button onClick={()=>void requestCloudAction("upload")} disabled={cloudBusy!==null}><Upload className="mr-2 h-4 w-4"/>{cloudBusy==="upload"?"A guardar...":"Guardar na cloud"}</Button><Button variant="outline" onClick={()=>void requestCloudAction("download")} disabled={cloudBusy!==null}><Download className="mr-2 h-4 w-4"/>{cloudBusy==="download"?"A carregar...":"Carregar da cloud"}</Button><Button variant="ghost" onClick={saveLocalBackup}>Backup local</Button></div></div>
 <Separator/><div><div className="text-sm font-semibold text-destructive">Zona de perigo</div>{!deleteMode?<Button className="mt-2" variant="destructive" onClick={()=>setDeleteMode(true)}>Eliminar conta</Button>:<div className="mt-2"><Input value={deleteConfirmation} onChange={e=>setDeleteConfirmation(e.target.value)} placeholder="apagar"/><Button className="mt-2" variant="destructive" onClick={handleDeleteAccount} disabled={deleteConfirmation!=="apagar"||deleting}>Eliminar permanentemente</Button><Button className="ml-2 mt-2" variant="outline" onClick={()=>setDeleteMode(false)}>Cancelar</Button></div>}</div></>}
 </CardContent></Card>;
}
