-- pg_net is required by Academic Hub private dispatch triggers.
-- On hosted Supabase this extension is owned by supabase_admin and is
-- non-relocatable. Do not recreate or move it only to silence the Advisor:
-- that would be a higher operational risk than the informational hardening gap.
--
-- Reviewed 2026-09-18:
-- * extension schema: public
-- * extrelocatable: false
-- * consumers: private.dispatch_security_incident_push,
--   private.dispatch_feedback_push, private.dispatch_puc_update_push,
--   private.dispatch_release_update_push, private.dispatch_survey_push,
--   private.dispatch_user_registration_push
-- * no client application code calls net.* directly.
--
-- The remaining Extension in Public WARN is therefore accepted as a managed
-- hosted-platform exception until Supabase exposes a supported relocation path.
select 1;
