-- Academic Hub — robustez final da cloud
-- Mantém até 10 versões por utilizador e publica user_state no Supabase Realtime.

create table if not exists public.user_state_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  state jsonb not null,
  source_updated_at timestamptz not null,
  created_at timestamptz not null default now(),
  device_label text,
  app_version text
);

create index if not exists user_state_history_user_created_idx
  on public.user_state_history (user_id, created_at desc);

alter table public.user_state_history enable row level security;
alter table public.user_state_history force row level security;

revoke all on table public.user_state_history from anon;
revoke insert, update, delete on table public.user_state_history from authenticated;
grant select on table public.user_state_history to authenticated;

drop policy if exists "user_state_history_select_own" on public.user_state_history;
create policy "user_state_history_select_own"
on public.user_state_history
for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.capture_user_state_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_state_history (
    user_id,
    state,
    source_updated_at,
    device_label,
    app_version
  ) values (
    new.user_id,
    new.state,
    new.updated_at,
    nullif(new.state #>> '{syncMeta,deviceLabel}', ''),
    nullif(new.state #>> '{meta,appVersion}', '')
  );

  delete from public.user_state_history history
  where history.user_id = new.user_id
    and history.id not in (
      select keep.id
      from public.user_state_history keep
      where keep.user_id = new.user_id
      order by keep.created_at desc, keep.id desc
      limit 10
    );

  return new;
end;
$$;

revoke execute on function public.capture_user_state_history() from public, anon, authenticated;

drop trigger if exists capture_user_state_history_after_write on public.user_state;
create trigger capture_user_state_history_after_write
after insert or update on public.user_state
for each row execute function public.capture_user_state_history();

-- Regista o estado atual como primeira versão de recuperação, sem duplicar
-- utilizadores que já tenham histórico por uma execução anterior desta migração.
insert into public.user_state_history (
  user_id,
  state,
  source_updated_at,
  device_label,
  app_version
)
select
  current_state.user_id,
  current_state.state,
  current_state.updated_at,
  nullif(current_state.state #>> '{syncMeta,deviceLabel}', ''),
  nullif(current_state.state #>> '{meta,appVersion}', '')
from public.user_state current_state
where not exists (
  select 1
  from public.user_state_history history
  where history.user_id = current_state.user_id
);

-- Supabase Realtime (Postgres Changes). Evita erro se a tabela já estiver publicada.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1
       from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'user_state'
     ) then
    execute 'alter publication supabase_realtime add table public.user_state';
  end if;
end
$$;
