create table if not exists public.push_delivery_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subscription_id uuid not null,
  device_label text,
  event_key text not null,
  status text not null check (status in ('accepted','error','gone')),
  status_code integer,
  attempt_count integer not null default 1 check (attempt_count > 0),
  last_error text,
  first_attempt_at timestamptz not null default now(),
  last_attempt_at timestamptz not null default now(),
  accepted_at timestamptz,
  unique (subscription_id, event_key)
);

comment on table public.push_delivery_attempts is 'Server-side Web Push delivery attempts per subscription and academic event. subscription_id is intentionally retained as an audit snapshot even if the subscription is later deleted.';
comment on column public.push_delivery_attempts.status is 'accepted = push service accepted the message; error = retryable or diagnostic failure; gone = endpoint returned 404/410 and was removed.';

create index if not exists push_delivery_attempts_user_event_idx
  on public.push_delivery_attempts (user_id, event_key);
create index if not exists push_delivery_attempts_retry_idx
  on public.push_delivery_attempts (status, last_attempt_at)
  where status = 'error';

alter table public.push_delivery_attempts enable row level security;
alter table public.push_delivery_attempts force row level security;
revoke all on table public.push_delivery_attempts from public, anon, authenticated;
grant select, insert, update, delete on table public.push_delivery_attempts to service_role;
revoke all on sequence public.push_delivery_attempts_id_seq from public, anon, authenticated;
grant usage, select on sequence public.push_delivery_attempts_id_seq to service_role;

select cron.alter_job(1, schedule := '0 8,11,14,17,20 * * *');
