create extension if not exists pg_net;
create extension if not exists pg_cron;

create table if not exists public.push_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  deadlines_enabled boolean not null default true,
  exams_enabled boolean not null default true,
  uab_enabled boolean not null default true,
  efinal_lead_days integer not null default 2 check (efinal_lead_days between 1 and 14),
  exam_lead_days integer not null default 7 check (exam_lead_days between 1 and 30),
  uab_lead_days integer not null default 3 check (uab_lead_days between 1 and 30),
  timezone text not null default 'Europe/Lisbon',
  updated_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  device_label text,
  user_agent text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions (user_id)
  where enabled = true;

create table if not exists public.push_delivery_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  sent_at timestamptz not null default now(),
  unique (user_id, event_key)
);

-- Configuração de servidor: sem privilégios para anon/authenticated.
-- Os valores sensíveis são inseridos diretamente em produção e nunca ficam no repositório.
create table if not exists public.push_server_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table public.push_preferences enable row level security;
alter table public.push_preferences force row level security;
alter table public.push_subscriptions enable row level security;
alter table public.push_subscriptions force row level security;
alter table public.push_delivery_log enable row level security;
alter table public.push_delivery_log force row level security;
alter table public.push_server_config enable row level security;
alter table public.push_server_config force row level security;

grant select, insert, update on public.push_preferences to authenticated;
grant select, insert, update, delete on public.push_subscriptions to authenticated;
revoke all on public.push_delivery_log from anon, authenticated;
revoke all on public.push_server_config from anon, authenticated;

create policy "push_preferences_select_own" on public.push_preferences
for select to authenticated using ((select auth.uid()) = user_id);
create policy "push_preferences_insert_own" on public.push_preferences
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "push_preferences_update_own" on public.push_preferences
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "push_subscriptions_select_own" on public.push_subscriptions
for select to authenticated using ((select auth.uid()) = user_id);
create policy "push_subscriptions_insert_own" on public.push_subscriptions
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "push_subscriptions_update_own" on public.push_subscriptions
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy "push_subscriptions_delete_own" on public.push_subscriptions
for delete to authenticated using ((select auth.uid()) = user_id);

create or replace function public.touch_push_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
revoke execute on function public.touch_push_updated_at() from public, anon, authenticated;

drop trigger if exists touch_push_preferences_updated_at on public.push_preferences;
create trigger touch_push_preferences_updated_at
before update on public.push_preferences
for each row execute function public.touch_push_updated_at();

drop trigger if exists touch_push_subscriptions_updated_at on public.push_subscriptions;
create trigger touch_push_subscriptions_updated_at
before update on public.push_subscriptions
for each row execute function public.touch_push_updated_at();

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.dispatch_academic_push_notifications()
returns void
language plpgsql
security definer
set search_path = public, extensions, private
as $$
declare
  function_url text;
  cron_secret text;
begin
  select value into function_url from public.push_server_config where key = 'function_url';
  select value into cron_secret from public.push_server_config where key = 'cron_secret';
  if function_url is null or cron_secret is null then
    return;
  end if;

  perform net.http_post(
    url := function_url,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', cron_secret
    ),
    body := '{"mode":"scheduled"}'::jsonb,
    timeout_milliseconds := 10000
  );
end;
$$;
revoke execute on function private.dispatch_academic_push_notifications() from public, anon, authenticated;
