// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { getPublicSupabaseConfig } from '@/lib/publicSupabaseConfig';
import type { Database } from './types';

const config = getPublicSupabaseConfig();
if (!config) {
  throw new Error('Supabase browser configuration is unavailable for this origin.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(config.supabaseUrl, config.supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});